
language: python
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
  - os: linux
    dist: xenial
  - os: windows

install:
  - pip install -r requiremetns.txt
  - pip install .

script:
- cd schema
- python TestValidate.py