
matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    language: sh
    env:
      - TOXENV=py3
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      - HOMEBREW_NO_ANALYTICS=1
    before_cache:
      # - brew cleanup
      - rm -f "$HOME/Library/Caches/pip/log/debug.log"
    cache:
      directories:
        # - "$HOME/Library/Caches/Homebrew"
        - "$HOME/Library/Caches/pip"
    addons:
      homebrew:
        # update: true
        packages: python3
    before_install:
      - python3 -m pip install pipenv
  - os: linux
    language: python
    python: "3.7"
    dist: xenial
  - os: windows
    language: sh
    python: "3.7"
    before_install:
      - choco install python3 --params "/InstallDir:C:\\Python"
      - export PATH="/c/Python:/c/Python/Scripts:$PATH"
      - python3 -m pip install pipenv

install:
  - pipenv install --dev

script:
- pipenv run pytest -v