[project]
name = "tk205"
version = "1.0.0"
description = ""
authors = [{ name = "Open205" }]
requires-python = ">=3.10"
dependencies = [
    "click",
    "jsonschema",
    "cbor2",
    "openpyxl",
    "pyyaml",
    "jinja2",
    "schema205",
]

[dependency-groups]
dev = ["pylint", "pytest", "markdown", "doit", "pygit2 >=1.15.1"]

[tool.uv]

[tool.uv.sources]
schema205 = { path = "schema-205", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
