# Copy all autogenerated source (cpp) files into build directory

file(GLOB autogenerated_sources "${PROJECT_SOURCE_DIR}/../schema-205/build/cpp/*.cpp")

foreach(filename ${autogenerated_sources})
    configure_file(${filename} ${PROJECT_SOURCE_DIR}/src/build/cpp COPYONLY)
endforeach(filename)

# Copy all autogenerated factory class headers into build directory - they won't be distributed

file(GLOB autogenerated_factories "${PROJECT_SOURCE_DIR}/../schema-205/build/include/*factory.h")

foreach(filename ${autogenerated_factories})
    configure_file(${filename} ${PROJECT_SOURCE_DIR}/src/build/include COPYONLY)
endforeach(filename)

# Copy the rest of the headers, for classes that must be distributed, into the project
# include directory

file(GLOB autogenerated_headers "${PROJECT_SOURCE_DIR}/../schema-205/build/include/*.h")
foreach(filename ${autogenerated_factories})
    list(REMOVE_ITEM autogenerated_headers ${filename})
endforeach(filename)

foreach(filename ${autogenerated_headers})
    configure_file(${filename} ${PROJECT_SOURCE_DIR}/include COPYONLY)
endforeach(filename)
