# Copy all autogenerated source (cpp) files into build directory

file(GLOB template_generated_files "${PROJECT_SOURCE_DIR}/../schema-205/schema205/src/*.h")

foreach(filename ${template_generated_files})
    configure_file(${filename} ${PROJECT_SOURCE_DIR}/include COPYONLY)
endforeach(filename)
