name: Build and Test

on: push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pipenv
        run: |
          python -m pip install pipenv
      - name: Install project
        run: |
          pipenv install --dev
      - name: Test
        run: |
          pipenv run pytest -v

