name: Build and Test

on: push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Install project
        run: pipenv install --dev
      - name: Build and test
        run: pipenv run doit
      - name: Upload web content
        uses: actions/upload-artifact@v2
        with:
          name: web-content-${{ matrix.os }}
          path: build/web
